### ISSUE TITLE
Version 3.0.0 

### ISSUE THREAD

**Issue by zimdin12** [wpcodefactory/eu-vat-for-woocommerce#3]
After updating to v3 I started geting this error.
Function get_cart was called <strong>incorrectly</strong>. Get basket should not be called before the wp_loaded action. Backtrace: require('wp-blog-header.php'), require_once('wp-load.php'), require_once('C:/laragon/www/my-site-name/web/wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook-&gt;do_action, WP_Hook-&gt;apply_filters, Alg_WC_EU_VAT_Core-&gt;maybe_exclude_vat, do_action('alg_wc_eu_vat_exempt_applied'), WP_Hook-&gt;do_action, WP_Hook-&gt;apply_filters, Alg_WC_EU_VAT_Core-&gt;handle_keep_vat_individual_product, WC_Cart-&gt;get_cart, wc_doing_it_wrong Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 2.3.)

Adding these lines to my controller helped but i haven't tested it this breaks something.

        if (!did_action('wp_loaded')) { // Tuntested hackfix for vat plugin 3.0.0
            remove_action('alg_wc_eu_vat_exempt_applied', [$algWcEuVat->core, 'handle_keep_vat_individual_product' ]);
        }

**Comment by BirendraMaharjan** [comment]
Hi @zimdin12,

Thanks for letting us know about the error. We’ve just released a new version of the plugin that should fix the issue you encountered with the cart function.

Please update to the latest version. it should work fine now. If you still run into any problems, just let us know.

Thank you.
